Config = {}

-- Franklin's house (3671 Whispymound Drive) — interior living room
-- Exterior door is ~7.12, 536.62, 176.03; interior shell is below that Z.
Config.CreatorCoords = vector4(3.1995, 529.7808, 170.3869, 113.0)
Config.CreatorCamOffset = vector3(0.0, 1.85, 0.45)

-- Ensure interior is visible (bob74_ipl Franklin interiorId 206849)
Config.CreatorInterior = {
    enabled = true,
    -- 'hills' = Vinewood Franklin mansion | 'aunt' = Forum Drive aunt house
    house = 'hills',
    hills = {
        coords = vector4(3.1995, 529.7808, 170.3869, 113.0),
        interiorId = 206849,
    },
    aunt = {
        -- Living room / hallway inside Forum Drive house
        coords = vector4(-14.17, -1441.45, 31.10, 0.0),
        interiorId = 197889,
    },
}

Config.MaxNameLength = 24
-- Fallback only — live limit comes from bsrp Config.MaxCharacters (export GetMaxCharacters)
Config.MaxCharacters = 5

-- Clothing-compatible skin is stored on bsrp_players.skin via exports.bsrp:SetSkin

Config.Spawns = {
    {
        id = 'last',
        label = 'Last Location',
        description = 'Continue where you left off',
        icon = '📍',
        useLast = true,
    },
    {
        id = 'legion',
        label = 'Legion Square',
        description = 'Downtown Los Santos',
        icon = '🏙',
        coords = vector4(195.17, -933.77, 30.69, 144.5),
    },
    {
        id = 'airport',
        label = 'LSIA Airport',
        description = 'South Los Santos',
        icon = '✈',
        coords = vector4(-1037.74, -2738.04, 20.17, 330.0),
    },
    {
        id = 'beach',
        label = 'Del Perro Beach',
        description = 'West coast freeroam',
        icon = '🌊',
        coords = vector4(-1850.1, -1231.8, 13.02, 320.0),
    },
    {
        id = 'paleto',
        label = 'Paleto Bay',
        description = 'Quiet northern town',
        icon = '🌲',
        coords = vector4(-448.45, 6008.2, 31.68, 45.0),
    },
    {
        id = 'sandy',
        label = 'Sandy Shores',
        description = 'Blaine County desert',
        icon = '🏜',
        coords = vector4(1961.2, 3740.5, 32.34, 300.0),
    },
    {
        id = 'mirror',
        label = 'Mirror Park',
        description = 'East LS residential',
        icon = '🏠',
        coords = vector4(1037.7, -764.5, 57.99, 145.0),
    },
    {
        id = 'vinewood',
        label = 'Vinewood Hills',
        description = 'Scenic overlook',
        icon = '🎬',
        coords = vector4(306.0, 177.5, 104.0, 160.0),
    },
}

-- Quick clothing presets applied after face setup
-- Component ids: 1 mask, 3 torso, 4 legs, 5 bag, 6 shoes, 7 accessory, 8 undershirt, 9 body armor, 10 decals, 11 top
-- Values: { drawable, texture }
Config.Presets = {
    male = {
        casual = {
            label = 'Casual',
            components = {
                [1] = { 0, 0 },
                [3] = { 15, 0 },
                [4] = { 14, 0 },
                [5] = { 0, 0 },
                [6] = { 1, 0 },
                [7] = { 0, 0 },
                [8] = { 15, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 15, 0 },
            },
        },
        street = {
            label = 'Street',
            components = {
                [1] = { 0, 0 },
                [3] = { 4, 0 },
                [4] = { 9, 0 },
                [5] = { 0, 0 },
                [6] = { 7, 0 },
                [7] = { 0, 0 },
                [8] = { 15, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 7, 0 },
            },
        },
        business = {
            label = 'Business',
            components = {
                [1] = { 0, 0 },
                [3] = { 1, 0 },
                [4] = { 10, 0 },
                [5] = { 0, 0 },
                [6] = { 10, 0 },
                [7] = { 0, 0 },
                [8] = { 31, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 10, 0 },
            },
        },
        athletic = {
            label = 'Athletic',
            components = {
                [1] = { 0, 0 },
                [3] = { 5, 0 },
                [4] = { 5, 0 },
                [5] = { 0, 0 },
                [6] = { 8, 0 },
                [7] = { 0, 0 },
                [8] = { 15, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 5, 0 },
            },
        },
        hoodie = {
            label = 'Hoodie',
            components = {
                [1] = { 0, 0 },
                [3] = { 4, 0 },
                [4] = { 1, 0 },
                [5] = { 0, 0 },
                [6] = { 1, 0 },
                [7] = { 0, 0 },
                [8] = { 15, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 57, 0 },
            },
        },
        smart = {
            label = 'Smart Casual',
            components = {
                [1] = { 0, 0 },
                [3] = { 11, 0 },
                [4] = { 24, 0 },
                [5] = { 0, 0 },
                [6] = { 10, 0 },
                [7] = { 0, 0 },
                [8] = { 15, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 26, 0 },
            },
        },
        formal = {
            label = 'Formal',
            components = {
                [1] = { 0, 0 },
                [3] = { 4, 0 },
                [4] = { 10, 0 },
                [5] = { 0, 0 },
                [6] = { 10, 0 },
                [7] = { 0, 0 },
                [8] = { 31, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 4, 0 },
            },
        },
        biker = {
            label = 'Biker',
            components = {
                [1] = { 0, 0 },
                [3] = { 4, 0 },
                [4] = { 4, 0 },
                [5] = { 0, 0 },
                [6] = { 12, 0 },
                [7] = { 0, 0 },
                [8] = { 15, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 64, 0 },
            },
        },
        beach = {
            label = 'Beach',
            components = {
                [1] = { 0, 0 },
                [3] = { 15, 0 },
                [4] = { 15, 0 },
                [5] = { 0, 0 },
                [6] = { 5, 0 },
                [7] = { 0, 0 },
                [8] = { 15, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 15, 0 },
            },
        },
        hipster = {
            label = 'Hipster',
            components = {
                [1] = { 0, 0 },
                [3] = { 14, 0 },
                [4] = { 7, 0 },
                [5] = { 0, 0 },
                [6] = { 14, 0 },
                [7] = { 0, 0 },
                [8] = { 15, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 74, 0 },
            },
        },
        party = {
            label = 'Party',
            components = {
                [1] = { 0, 0 },
                [3] = { 14, 0 },
                [4] = { 24, 0 },
                [5] = { 0, 0 },
                [6] = { 10, 0 },
                [7] = { 0, 0 },
                [8] = { 15, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 33, 0 },
            },
        },
        workwear = {
            label = 'Workwear',
            components = {
                [1] = { 0, 0 },
                [3] = { 0, 0 },
                [4] = { 0, 0 },
                [5] = { 0, 0 },
                [6] = { 24, 0 },
                [7] = { 0, 0 },
                [8] = { 15, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 0, 0 },
            },
        },
        racer = {
            label = 'Racer',
            components = {
                [1] = { 0, 0 },
                [3] = { 4, 0 },
                [4] = { 9, 0 },
                [5] = { 0, 0 },
                [6] = { 7, 0 },
                [7] = { 0, 0 },
                [8] = { 15, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 55, 0 },
            },
        },
        winter = {
            label = 'Winter',
            components = {
                [1] = { 0, 0 },
                [3] = { 4, 0 },
                [4] = { 4, 0 },
                [5] = { 0, 0 },
                [6] = { 12, 0 },
                [7] = { 0, 0 },
                [8] = { 15, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 88, 0 },
            },
        },
        sleeveless = {
            label = 'Tank',
            components = {
                [1] = { 0, 0 },
                [3] = { 5, 0 },
                [4] = { 5, 0 },
                [5] = { 0, 0 },
                [6] = { 5, 0 },
                [7] = { 0, 0 },
                [8] = { 15, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 16, 0 },
            },
        },
        open_shirt = {
            label = 'Open Shirt',
            components = {
                [1] = { 0, 0 },
                [3] = { 4, 0 },
                [4] = { 1, 0 },
                [5] = { 0, 0 },
                [6] = { 1, 0 },
                [7] = { 0, 0 },
                [8] = { 15, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 22, 0 },
            },
        },
    },
    female = {
        casual = {
            label = 'Casual',
            components = {
                [1] = { 0, 0 },
                [3] = { 15, 0 },
                [4] = { 14, 0 },
                [5] = { 0, 0 },
                [6] = { 3, 0 },
                [7] = { 0, 0 },
                [8] = { 14, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 18, 0 },
            },
        },
        street = {
            label = 'Street',
            components = {
                [1] = { 0, 0 },
                [3] = { 9, 0 },
                [4] = { 6, 0 },
                [5] = { 0, 0 },
                [6] = { 1, 0 },
                [7] = { 0, 0 },
                [8] = { 14, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 9, 0 },
            },
        },
        business = {
            label = 'Business',
            components = {
                [1] = { 0, 0 },
                [3] = { 1, 0 },
                [4] = { 6, 0 },
                [5] = { 0, 0 },
                [6] = { 0, 0 },
                [7] = { 0, 0 },
                [8] = { 39, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 7, 0 },
            },
        },
        athletic = {
            label = 'Athletic',
            components = {
                [1] = { 0, 0 },
                [3] = { 14, 0 },
                [4] = { 10, 0 },
                [5] = { 0, 0 },
                [6] = { 3, 0 },
                [7] = { 0, 0 },
                [8] = { 14, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 14, 0 },
            },
        },
        hoodie = {
            label = 'Hoodie',
            components = {
                [1] = { 0, 0 },
                [3] = { 3, 0 },
                [4] = { 1, 0 },
                [5] = { 0, 0 },
                [6] = { 1, 0 },
                [7] = { 0, 0 },
                [8] = { 14, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 49, 0 },
            },
        },
        elegant = {
            label = 'Elegant',
            components = {
                [1] = { 0, 0 },
                [3] = { 3, 0 },
                [4] = { 8, 0 },
                [5] = { 0, 0 },
                [6] = { 8, 0 },
                [7] = { 0, 0 },
                [8] = { 14, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 23, 0 },
            },
        },
        party = {
            label = 'Party',
            components = {
                [1] = { 0, 0 },
                [3] = { 4, 0 },
                [4] = { 8, 0 },
                [5] = { 0, 0 },
                [6] = { 8, 0 },
                [7] = { 0, 0 },
                [8] = { 14, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 31, 0 },
            },
        },
        beach = {
            label = 'Beach',
            components = {
                [1] = { 0, 0 },
                [3] = { 15, 0 },
                [4] = { 15, 0 },
                [5] = { 0, 0 },
                [6] = { 5, 0 },
                [7] = { 0, 0 },
                [8] = { 14, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 15, 0 },
            },
        },
        chic = {
            label = 'Chic',
            components = {
                [1] = { 0, 0 },
                [3] = { 3, 0 },
                [4] = { 4, 0 },
                [5] = { 0, 0 },
                [6] = { 13, 0 },
                [7] = { 0, 0 },
                [8] = { 14, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 3, 0 },
            },
        },
        formal = {
            label = 'Formal',
            components = {
                [1] = { 0, 0 },
                [3] = { 1, 0 },
                [4] = { 6, 0 },
                [5] = { 0, 0 },
                [6] = { 0, 0 },
                [7] = { 0, 0 },
                [8] = { 39, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 58, 0 },
            },
        },
        summer = {
            label = 'Summer',
            components = {
                [1] = { 0, 0 },
                [3] = { 15, 0 },
                [4] = { 12, 0 },
                [5] = { 0, 0 },
                [6] = { 5, 0 },
                [7] = { 0, 0 },
                [8] = { 14, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 2, 0 },
            },
        },
        racer = {
            label = 'Racer',
            components = {
                [1] = { 0, 0 },
                [3] = { 3, 0 },
                [4] = { 1, 0 },
                [5] = { 0, 0 },
                [6] = { 1, 0 },
                [7] = { 0, 0 },
                [8] = { 14, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 74, 0 },
            },
        },
        winter = {
            label = 'Winter',
            components = {
                [1] = { 0, 0 },
                [3] = { 3, 0 },
                [4] = { 1, 0 },
                [5] = { 0, 0 },
                [6] = { 1, 0 },
                [7] = { 0, 0 },
                [8] = { 14, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 88, 0 },
            },
        },
        crop = {
            label = 'Crop Top',
            components = {
                [1] = { 0, 0 },
                [3] = { 15, 0 },
                [4] = { 1, 0 },
                [5] = { 0, 0 },
                [6] = { 1, 0 },
                [7] = { 0, 0 },
                [8] = { 14, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 111, 0 },
            },
        },
        dress = {
            label = 'Dress',
            components = {
                [1] = { 0, 0 },
                [3] = { 4, 0 },
                [4] = { 8, 0 },
                [5] = { 0, 0 },
                [6] = { 8, 0 },
                [7] = { 0, 0 },
                [8] = { 14, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 78, 0 },
            },
        },
        open_jacket = {
            label = 'Jacket',
            components = {
                [1] = { 0, 0 },
                [3] = { 3, 0 },
                [4] = { 4, 0 },
                [5] = { 0, 0 },
                [6] = { 1, 0 },
                [7] = { 0, 0 },
                [8] = { 14, 0 },
                [9] = { 0, 0 },
                [10] = { 0, 0 },
                [11] = { 8, 0 },
            },
        },
    },
}

-- Face feature labels for NUI
Config.FaceFeatures = {
    { id = 0, label = 'Nose Width' },
    { id = 1, label = 'Nose Peak' },
    { id = 2, label = 'Nose Length' },
    { id = 3, label = 'Nose Bone Curve' },
    { id = 4, label = 'Nose Tip' },
    { id = 5, label = 'Nose Twist' },
    { id = 6, label = 'Brow Height' },
    { id = 7, label = 'Brow Depth' },
    { id = 8, label = 'Cheek Height' },
    { id = 9, label = 'Cheek Width' },
    { id = 10, label = 'Cheek Width 2' },
    { id = 11, label = 'Eyes' },
    { id = 12, label = 'Lips' },
    { id = 13, label = 'Jaw Width' },
    { id = 14, label = 'Jaw Shape' },
    { id = 15, label = 'Chin Height' },
    { id = 16, label = 'Chin Length' },
    { id = 17, label = 'Chin Width' },
    { id = 18, label = 'Chin Dimple' },
    { id = 19, label = 'Neck Width' },
}
